# Docker Compose to run databases for dev
version: '3.9'
services:
  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - './data/redis:/data'

  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'dev'
      POSTGRES_PASSWORD: '123'
    volumes:
      - './data/pg:/var/lib/postgresql/data'
